# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """\
$character\
$jobs\
$git_commit\
$username\
$hostname\
$directory"""
right_format = """\
$rust\
$git_status\
$git_state\
$git_branch\
$git_metrics \
$time\
$battery\
"""

command_timeout = 750

[directory]
style = "bold blue"

[line_break]
disabled = true

[hostname]
format = '[$hostname](bold #b23737) '

[username]
format = "[$user]()@"

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[●](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[●](bold red)'
success_symbol = '[●](green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_metrics]
disabled = false

[git_status]
format = '[$all_status$ahead_behind]($style)'

[time]
format = '[\[$time\]]()'
disabled = false

[rust]
format = '[$symbol($version)]($style) '
disabled = false

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'
disabled = false
show_notifications = true

[[battery.display]]
threshold = 70
